// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using evalflow_backend_api.Infrastructure.Database;

#nullable disable

namespace evalflow_backend_api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829123744_UpdateAnswerForEncryption")]
    partial class UpdateAnswerForEncryption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvaluationCycleTemplate", b =>
                {
                    b.Property<int>("CiclosId")
                        .HasColumnType("integer");

                    b.Property<int>("TemplatesId")
                        .HasColumnType("integer");

                    b.HasKey("CiclosId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("EvaluationCycleTemplate");
                });

            modelBuilder.Entity("TemplateTemplateFavoriteList", b =>
                {
                    b.Property<int>("ListasFavoritasId")
                        .HasColumnType("integer");

                    b.Property<int>("TemplatesId")
                        .HasColumnType("integer");

                    b.HasKey("ListasFavoritasId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("TemplateTemplateFavoriteList");
                });

            modelBuilder.Entity("TemplateUser", b =>
                {
                    b.Property<int>("TemplatesAsignadosId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariosAsignadosId")
                        .HasColumnType("integer");

                    b.HasKey("TemplatesAsignadosId", "UsuariosAsignadosId");

                    b.HasIndex("UsuariosAsignadosId");

                    b.ToTable("TemplateUser");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvaluationSubmissionId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("OpcionesSeleccionadas")
                        .HasColumnType("text[]");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ValorNumerico")
                        .HasColumnType("integer");

                    b.Property<string>("ValorTexto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationSubmissionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("DireccionFiscal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentificationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.EvaluationCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaID");

                    b.ToTable("EvaluationCycles");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.EvaluationSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluatedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("EvaluationCycleId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RespondentUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedUserId");

                    b.HasIndex("EvaluationCycleId");

                    b.HasIndex("RespondentUserId");

                    b.HasIndex("TemplateId");

                    b.ToTable("EvaluationSubmissions");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaID");

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Opciones")
                        .HasColumnType("text[]");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.RoleFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleFeatures");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.TemplateFavoriteList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TemplateFavoriteLists");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("CargoId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiracionTokenRecuperacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SuperiorId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenInvitacion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenInvitacionExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenRecuperacionPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TokenValidacionEmail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenValidacionExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwoFactorCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TwoFactorCodeExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaID");

                    b.HasIndex("SuperiorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EvaluationCycleTemplate", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.EvaluationCycle", null)
                        .WithMany()
                        .HasForeignKey("CiclosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemplateTemplateFavoriteList", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.TemplateFavoriteList", null)
                        .WithMany()
                        .HasForeignKey("ListasFavoritasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemplateUser", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplatesAsignadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsuariosAsignadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Answer", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.EvaluationSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("EvaluationSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Department", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Company", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.EvaluationCycle", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Company", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.EvaluationSubmission", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.User", "EvaluatedUser")
                        .WithMany("EvaluacionesRecibidas")
                        .HasForeignKey("EvaluatedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.EvaluationCycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("EvaluationCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.User", "RespondentUser")
                        .WithMany("EvaluacionesRealizadas")
                        .HasForeignKey("RespondentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("EvaluatedUser");

                    b.Navigation("RespondentUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.JobPosition", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Company", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Question", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Template", "Template")
                        .WithMany("Preguntas")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.RoleFeature", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Role", "Role")
                        .WithMany("Features")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Template", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.Company", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.TemplateFavoriteList", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.User", "Usuario")
                        .WithMany("ListasFavoritas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.User", b =>
                {
                    b.HasOne("evalflow_backend_api.Domain.Entities.JobPosition", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId");

                    b.HasOne("evalflow_backend_api.Domain.Entities.Department", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("evalflow_backend_api.Domain.Entities.Company", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evalflow_backend_api.Domain.Entities.User", "Superior")
                        .WithMany("Subordinados")
                        .HasForeignKey("SuperiorId");

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");

                    b.Navigation("Empresa");

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Company", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Department", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.EvaluationSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.JobPosition", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Role", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.Template", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("evalflow_backend_api.Domain.Entities.User", b =>
                {
                    b.Navigation("EvaluacionesRealizadas");

                    b.Navigation("EvaluacionesRecibidas");

                    b.Navigation("ListasFavoritas");

                    b.Navigation("Subordinados");
                });
#pragma warning restore 612, 618
        }
    }
}
